export const timezonesDB = {
  ET: ['America/New_York'],
  CT: ['America/Chicago'],
  MT: ['America/Denver'],
  PT: ['America/Los_Angeles'],
  AK: ['America/Anchorage'],
  HAST: ['Pacific/Honolulu'],
  MST: ['America/Phoenix'],
  AST: ['America/Aruba', 'America/Moncton', 'Atlantic/Bermuda', 'America/Santo_Domingo'],
  MOST: ['Africa/Casablanca'],
  UTC: ['Etc/GMT+0'],
  GMT: ['Europe/London', 'Europe/Dublin', 'Europe/Edinburgh', 'Europe/Lisbon'],
  GST: ['Africa/Monrovia', 'Atlantic/Reykjavik'],
  WET: [
    'Europe/Amsterdam',
    'Europe/Berlin',
    'Europe/Bern',
    'Europe/Rome',
    'Europe/Stockholm',
    'Europe/Vienna'
  ],
  CET: [
    'Europe/Belgrade',
    'Europe/Bratislava',
    'Europe/Budapest',
    'Europe/Ljubljana',
    'Europe/Prague'
  ],
  RST: ['Europe/Brussels', 'Europe/Copenhagen', 'Europe/Madrid', 'Europe/Paris'],
  CEST: ['Europe/Sarajevo', 'Europe/Skopje', 'Europe/Warsaw', 'Europe/Zagreb'],
  ECT: ['Africa/Brazzaville', 'Africa/Douala'],
  JST: ['Asia/Amman'],
  GTBST: ['Europe/Bucharest', 'Europe/Athens', 'Europe/Istanbul'],
  MEST: ['Africa/Cairo', 'Asia/Beirut'],
  EGST: ['Africa/Cairo'],
  SST: ['Asia/Damascus'],
  SAST: ['Africa/Johannesburg', 'Africa/Harare'],
  EET: [
    'Europe/Helsinki',
    'Europe/Kyiv',
    'Europe/Riga',
    'Europe/Sofia',
    'Europe/Tallinn',
    'Europe/Vilnius'
  ],
  ISST: ['Asia/Jerusalem'],
  EEST: ['Europe/Minsk'],
  NMST: ['Africa/Windhoek'],
  ARST: ['Asia/Baghdad'],
  ABST: ['Asia/Kuwait', 'Asia/Riyadh'],
  MSK: ['Europe/Moscow', 'Europe/St. Petersburg', 'Europe/Volgograd'],
  EAT: ['Africa/Nairobi'],
  IRST: ['Asia/Tehran'],
  ARBST: ['Asia/Dubai', 'Asia/Muscat'],
  AZT: ['Asia/Baku'],
  MUT: ['Indian/Mauritius'],
  GET: ['Asia/Tbilisi'],
  AMT: ['Asia/Yerevan'],
  AFT: ['Asia/Kabul'],
  YEKT: ['Asia/Yekaterinburg'],
  PKT: ['Asia/Karachi'],
  WAST: ['Asia/Tashkent', 'Asia/Yekaterinburg'],
  UZT: ['Asia/Tashkent'],
  IST: ['Asia/Calcutta', 'Asia/Chennai', 'Asia/Kolkata', 'Asia/Mumbai', 'Asia/New_Delhi'],
  SLT: ['Asia/Sri_Jayawardenepura', 'Asia/Calcutta'],
  NPT: ['Asia/Katmandu'],
  BTT: ['Asia/Astana', 'Asia/Dhaka'],
  BST: ['Asia/Dhaka'],
  NCAST: ['Asia/Novosibirsk', 'Asia/Almaty'],
  MYST: ['Asia/Rangoon', 'Asia/Yangon'],
  THA: ['Asia/Bangkok', 'Asia/Hanoi', 'Asia/Jakarta'],
  KRAT: ['Asia/Krasnoyarsk'],
  IRKT: ['Asia/Irkutsk'],
  SNST: ['Asia/Kuala_Lumpur', 'Asia/Singapore'],
  AWST: ['Australia/Perth'],
  TIST: ['Asia/Taipei'],
  UST: ['Asia/Ulaanbaatar'],
  TST: ['Asia/Tokyo', 'Asia/Osaka', 'Asia/Sapporo'],
  KST: ['Asia/Seoul'],
  YAKT: ['Asia/Yakutsk'],
  CAUST: ['Australia/Adelaide'],
  ACST: ['Australia/Darwin'],
  EAST: ['Australia/Brisbane'],
  AEST: ['Australia/Canberra', 'Australia/Melbourne', 'Australia/Sydney'],
  WPST: ['Pacific/Guam', 'Pacific/Port_Moresby'],
  TAST: ['Australia/Hobart'],
  VLAT: ['Asia/Vladivostok'],
  SBT: ['Pacific/Solomon Is.', 'Pacific/New_Caledonia', 'Asia/Magadan', 'Pacific/Guadalcanal'],
  NZST: ['Pacific/Auckland'],
  UTC12: ['Etc/GMT-12'],
  FJT: ['Pacific/Fiji'],
  PETT: ['Asia/Kamchatka'],
  PHOT: ['Pacific/Tongatapu'],
  AZOST: ['Atlantic/Azores'],
  CVT: ['Atlantic/Cape_Verde'],
  ESAST: ['America/Sao_Paulo'],
  ART: ['America/Buenos Aires'],
  SAEST: ['America/Cayenne', 'America/Fortaleza'],
  GNST: ['America/Godthab'],
  MVST: ['America/Montevideo'],
  NST: ['Canada/Newfoundland'],
  PRST: ['America/Asuncion'],
  CBST: ['America/Cuiaba'],
  SAWST: ['America/La_Paz', 'America/Manaus', 'America/Argentina/San_Juan', 'America/Guyana'],
  PSAST: ['America/Santiago'],
  VST: ['America/Caracas'],
  SAPST: ['America/Bogota', 'America/Lima', 'America/Guayaquil'],
  EST: ['America/Halifax', 'America/Indiana/Indianapolis'],
  CAST: ['America/El_Salvador', 'America/Mexico_City'],
  CST: ['America/Monterrey', 'America/Mexico_City'],
  CCST: ['Canada/Saskatchewan'],
  MSTM: ['America/Chihuahua', 'America/Mazatlan'],
  PST: ['America/Los_Angeles'],
  SMST: ['Pacific/Pago_Pago', 'Pacific/Apia'],
  BIT: ['Etc/GMT+12']
};
