export const timezonesDB = {
  ET: ['America/New_York'],
  CT: ['America/Chicago'],
  MT: ['America/Denver'],
  PT: ['America/Los_Angeles'],
  AK: ['America/Anchorage'],
  HAST: ['Pacific/Honolulu'],
  MST: ['America/Phoenix'],
  AST: ['America/Aruba', 'America/Moncton', 'Atlantic/Bermuda', 'America/Santo_Domingo'],
  MOST: ['Africa/Casablanca'],
  UTC: [
    'Africa/Ouagadougou',
    'Africa/Banjul',
    'Africa/Bissau',
    'Africa/Abidjan',
    'Africa/Monrovia',
    'Africa/Nouakchott',
    'Africa/Dakar',
    'Africa/Accra',
    'Africa/Conakry',
    'Africa/Bamako',
    'Africa/Sao_Tome',
    'Africa/Freetown',
    'Africa/Lome',
    'Atlantic/Faroe',
    'Atlantic/Reykjavik',
    'Europe/Isle_of_Man',
    'Europe/London',
    'Europe/Dublin',
    'Europe/Edinburgh',
    'Europe/Lisbon'
  ],
  GMT: [
    'Europe/London',
    'Europe/Dublin',
    'Europe/Edinburgh',
    'Europe/Lisbon',
    'Europe/Isle_of_Man',
    'Africa/Ouagadougou',
    'Africa/Banjul',
    'Africa/Bissau',
    'Africa/Abidjan',
    'Africa/Monrovia',
    'Africa/Nouakchott',
    'Africa/Dakar',
    'Africa/Accra',
    'Africa/Conakry',
    'Africa/Bamako',
    'Africa/Sao_Tome',
    'Africa/Freetown',
    'Africa/Lome',
    'Atlantic/Reykjavik',
    'Atlantic/Faroe'
  ],
  WET: ['Atlantic/Faroe', 'Europe/Lisbon'],
  CET: [
    'Europe/Amsterdam',
    'Europe/Berlin',
    'Europe/Bern',
    'Europe/Rome',
    'Europe/Stockholm',
    'Europe/Vienna',
    'Europe/Belgrade',
    'Europe/Bratislava',
    'Europe/Budapest',
    'Europe/Ljubljana',
    'Europe/Prague',
    'Europe/Tirane',
    'Europe/Andorra',
    'Europe/Brussels',
    'Europe/Sarajevo',
    'Europe/Zagreb',
    'Europe/Copenhagen',
    'Europe/Madrid',
    'Europe/Paris',
    'Europe/Gibraltar',
    'Europe/Brussels',
    'Europe/Vaduz',
    'Europe/Luxembourg',
    'Europe/Skopje',
    'Europe/Warsaw',
    'Europe/Podgorica',
    'Europe/Oslo',
    'Europe/San_Marino',
    'Africa/Algiers',
    'Africa/Tunis'
  ],
  MET: [
    'Europe/Amsterdam',
    'Europe/Berlin',
    'Europe/Bern',
    'Europe/Rome',
    'Europe/Stockholm',
    'Europe/Vienna',
    'Europe/Belgrade',
    'Europe/Bratislava',
    'Europe/Budapest',
    'Europe/Ljubljana',
    'Europe/Prague',
    'Europe/Tirane',
    'Europe/Andorra',
    'Europe/Brussels',
    'Europe/Sarajevo',
    'Europe/Zagreb',
    'Europe/Copenhagen',
    'Europe/Madrid',
    'Europe/Paris',
    'Europe/Gibraltar',
    'Europe/Brussels',
    'Europe/Vaduz',
    'Europe/Luxembourg',
    'Europe/Skopje',
    'Europe/Warsaw',
    'Europe/Podgorica',
    'Europe/Oslo',
    'Europe/San_Marino',
    'Africa/Algiers',
    'Africa/Tunis'
  ],
  CEST: [
    'Europe/Amsterdam',
    'Europe/Berlin',
    'Europe/Bern',
    'Europe/Rome',
    'Europe/Stockholm',
    'Europe/Vienna',
    'Europe/Belgrade',
    'Europe/Bratislava',
    'Europe/Budapest',
    'Europe/Ljubljana',
    'Europe/Prague',
    'Europe/Tirane',
    'Europe/Andorra',
    'Europe/Brussels',
    'Europe/Sarajevo',
    'Europe/Zagreb',
    'Europe/Copenhagen',
    'Europe/Madrid',
    'Europe/Paris',
    'Europe/Gibraltar',
    'Europe/Brussels',
    'Europe/Vaduz',
    'Europe/Luxembourg',
    'Europe/Skopje',
    'Europe/Warsaw',
    'Europe/Podgorica',
    'Europe/Oslo',
    'Europe/San_Marino',
    'Africa/Algiers',
    'Africa/Tunis'
  ],
  WAT: [
    'Africa/Luanda',
    'Africa/Porto-Novo',
    'Africa/Bangui',
    'Africa/Ndjamena',
    'Africa/Kinshasa',
    'Africa/Malabo',
    'Africa/Libreville',
    'Africa/Niamey',
    'Africa/Lagos',
    'Africa/Brazzaville',
    'Africa/Douala'
  ],
  JST: ['Asia/Amman'],
  GTBST: ['Europe/Minsk', 'Europe/Athens', 'Europe/Istanbul'],
  MEST: [
    'Asia/Damascus',
    'Africa/Windhoek',
    'Asia/Jerusalem',
    'Africa/Cairo',
    'Asia/Beirut',
    'Asia/Amman',
    'Africa/Tripoli',
    'Asia/Hebron'
  ],
  EGST: ['Africa/Cairo'],
  SST: ['Asia/Damascus'],
  SAST: ['Africa/Johannesburg', 'Africa/Harare', 'Africa/Maseru'],
  EET: [
    'Asia/Nicosia',
    'Europe/Athens',
    'Europe/Bucharest',
    'Europe/Helsinki',
    'Europe/Kiev',
    'Europe/Kaliningrad',
    'Europe/Riga',
    'Europe/Sofia',
    'Europe/Tallinn',
    'Europe/Vilnius',
    'Europe/Chisinau'
  ],
  TRT: ['Europe/Istanbul'],
  ISST: ['Asia/Jerusalem'],
  EEST: [
    'Asia/Nicosia',
    'Europe/Athens',
    'Europe/Bucharest',
    'Europe/Helsinki',
    'Europe/Kiev',
    'Europe/Kaliningrad',
    'Europe/Riga',
    'Europe/Sofia',
    'Europe/Tallinn',
    'Europe/Vilnius',
    'Europe/Chisinau'
  ],
  NMST: ['Africa/Windhoek'],
  ARST: ['Asia/Baghdad', 'Asia/Bahrain', 'Asia/Kuwait', 'Asia/Qatar', 'Asia/Riyadh', 'Asia/Aden'],
  ABST: ['Asia/Baghdad', 'Asia/Bahrain', 'Asia/Kuwait', 'Asia/Qatar', 'Asia/Riyadh', 'Asia/Aden'],
  MSK: ['Europe/Moscow', 'Europe/St. Petersburg', 'Europe/Volgograd', 'Europe/Minsk'],
  EAT: [
    'Africa/Nairobi',
    'Indian/Comoro',
    'Indian/Antananarivo',
    'Africa/Djibouti',
    'Africa/Asmara',
    'Africa/Addis_Ababa',
    'Africa/Mogadishu',
    'Africa/Dar_es_Salaam',
    'Africa/Kampala'
  ],
  IRST: ['Asia/Tehran'],
  GST: ['Asia/Dubai', 'Asia/Muscat'],
  AZT: ['Asia/Baku'],
  MUT: ['Indian/Mauritius'],
  GET: ['Asia/Tbilisi'],
  AMT: ['Asia/Yerevan'],
  AFT: ['Asia/Kabul'],
  YEKT: ['Asia/Yekaterinburg'],
  PKT: ['Asia/Karachi'],
  WAST: ['Asia/Tashkent', 'Asia/Ashgabat', 'Asia/Yekaterinburg'],
  UZT: ['Asia/Tashkent'],
  TT: ['Asia/Dushanbe'],
  IST: ['Asia/Chennai', 'Asia/Kolkata', 'Asia/Mumbai', 'Asia/New_Delhi'],
  SLT: ['Asia/Colombo'],
  NPT: ['Asia/Kathmandu'],
  BST: ['Asia/Dhaka'],
  NCAST: ['Asia/Novosibirsk', 'Asia/Almaty'],
  MYST: ['Asia/Rangoon', 'Asia/Yangon'],
  THA: ['Asia/Bangkok', 'Asia/Hanoi', 'Asia/Jakarta'],
  KRAT: ['Asia/Krasnoyarsk'],
  IRKT: ['Asia/Irkutsk'],
  SNST: ['Asia/Kuala_Lumpur', 'Asia/Singapore'],
  AWST: ['Australia/Perth'],
  TIST: ['Asia/Taipei'],
  UST: ['Asia/Ulaanbaatar'],
  TST: ['Asia/Tokyo', 'Asia/Osaka', 'Asia/Sapporo'],
  KST: ['Asia/Seoul'],
  YAKT: ['Asia/Yakutsk'],
  CAUST: ['Australia/Adelaide'],
  ACST: ['Australia/Darwin'],
  EAST: ['Australia/Brisbane'],
  AEST: ['Australia/Canberra', 'Australia/Melbourne', 'Australia/Sydney'],
  WPST: ['Pacific/Guam', 'Pacific/Port_Moresby'],
  TAST: ['Australia/Hobart'],
  VLAT: ['Asia/Vladivostok'],
  CPST: ['Pacific/New_Caledonia', 'Asia/Magadan', 'Pacific/Guadalcanal'],
  NZST: ['Pacific/Auckland'],
  'UTC+12': [
    'Pacific/Fiji',
    'Asia/Kamchatka',
    'Pacific/Majuro',
    'Asia/Anadyr',
    'Asia/Tarawa',
    'Pacific/Funafuti'
  ],
  FJT: ['Pacific/Fiji'],
  CAT: [
    'Africa/Gaborone',
    'Africa/Bujumbura',
    'Africa/Lubumbashi',
    'Africa/Blantyre',
    'Africa/Lusaka',
    'Africa/Windhoek',
    'Africa/Kigali',
    'Africa/Juba',
    'Africa/Khartoum',
    'Africa/Lusaka',
    'Africa/Harare'
  ],
  PETT: ['Asia/Kamchatka'],
  TOT: ['Pacific/Tongatapu'],
  AZOST: ['Atlantic/Azores'],
  CVT: ['Atlantic/Cape_Verde'],
  ESAST: ['America/Sao_Paulo'],
  ART: ['America/Buenos Aires'],
  SAEST: ['America/Cayenne', 'America/Fortaleza'],
  GNST: ['America/Godthab'],
  MVST: ['America/Montevideo'],
  NST: ['Canada/Newfoundland'],
  PRST: ['America/Asuncion'],
  CBST: ['America/Cuiaba'],
  SAWST: ['America/La_Paz', 'America/Manaus', 'America/Argentina/San_Juan', 'America/Guyana'],
  PSAST: ['America/Santiago'],
  VST: ['America/Caracas'],
  SAPST: ['America/Bogota', 'America/Lima', 'America/Guayaquil'],
  EST: [
    'America/New_York',
    'America/Detroit',
    'America/Iqaluit',
    'America/Montreal',
    'America/Halifax',
    'America/Indiana/Indianapolis',
    'America/Jamaica',
    'America/Panama',
    'America/Nassau',
    'America/Port-au-Prince'
  ],
  CAST: ['America/El_Salvador', 'America/Mexico_City'],
  CST: ['America/Monterrey', 'America/Mexico_City'],
  CCST: ['Canada/Regina'],
  MSTM: ['America/Chihuahua', 'America/Mazatlan'],
  PST: ['America/Los_Angeles'],
  SMST: ['Pacific/Pago_Pago', 'Pacific/Apia']
};
